<?php
/**
 * @var $this Bubble_Launcher_Block_Adminhtml_Launcher
 */
?>
<?php if ($this->isEnabled()): ?>
    <script type="text/javascript">
        Event.observe(window, 'load', function() {
            $('nav').insert('<li id="bubblelauncher-status"><a id="bubblelauncher-icon" href="http://bubbleco.de" target="_blank" title="BubbleCode">&nbsp;</li>');
            var launcher = new BubbleLauncher({
                dataLocation: '<?php echo $this->helper('adminhtml')->getUrl('adminhtml/bubble_launcher/index') ?>',
                onReady: function() {
                    $('bubblelauncher-status').addClassName('on');
                },
                onError: function(error) {
                    $('bubblelauncher-icon').title = error.replace(/"/g, '&quot;');
                },
                minChars: <?php echo $this->getMinChars(); ?>,
                maxResults: <?php echo $this->getMaxResults(); ?>,
                resetOnHide: <?php echo $this->getResetOnHide(); ?>,
                useScope: <?php echo $this->getUseScope(); ?>,
                showIcon: <?php echo $this->getShowIcon(); ?>,
                showScope: <?php echo $this->getShowScope(); ?>,
                showText: <?php echo $this->getShowText(); ?>
            });
            $('bubblelauncher-icon').observe('click', launcher.show.bind(launcher));
        });
    </script>
<?php endif; ?>