<?php
/**
 * @var $this Bubble_Launcher_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('http://i.imgur.com/NtYmWIh.png') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/jreinke/magento-admin-launcher" target="_blank" style="float:right;">
            <img src="http://i.imgur.com/QVKwCFx.png" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('bubble_launcher')->__('Bubble Launcher is an intuitive and powerful keystroke launcher for Magento Admin Panel.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('bubble_launcher')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('bubble_launcher')->__('http://bubbleco.de/en/2013/03/25/a-powerful-launcher-for-magento-admin-panel/')); ?>" target="_blank"><?php echo $this->helper('bubble_launcher')->__('here'); ?></a>.</p>
    </div>
</div>